version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_DATABASE=node-all-test
      - MYSQL_PASSWORD=Password.123
      - MYSQL_ROOT_PASSWORD=Password.123
    ports:
      - '3307:3306'
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  # app:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   restart: unless-stopped
  #   links:
  #     - db
  #   env_file: .env
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=Password.123
  #     - DB_DATABASE=node-all-test
  #   depends_on:
  #     - db
volumes:
  my-db:
